
try { main.main_BANG_(); } catch (e) { console.error("An error occurred when calling (main/main!)"); throw(e); }